# Generated by Django 6.0.3 on 2026-03-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('crop', models.CharField(blank=True, max_length=100)),
                ('land_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('total_records', models.IntegerField(default=0)),
                ('success_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team1Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('call_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy / Call Back')], default='pending', max_length=20)),
                ('interest_status', models.CharField(choices=[('not_called', 'Not Called Yet'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('no_response', 'No Response')], default='not_called', max_length=20)),
                ('call_remarks', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'team1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_farmers', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team1_assignment', to='core.farmer')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Team2Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('followup_status', models.CharField(choices=[('pending', 'Pending Contact'), ('contacted', 'Contacted'), ('not_reachable', 'Not Reachable')], default='pending', max_length=20)),
                ('final_response', models.CharField(choices=[('awaiting', 'Awaiting Response'), ('confirmed', 'Confirmed / Converted'), ('declined', 'Declined'), ('callback', 'Will Call Back'), ('no_response', 'No Response')], default='awaiting', max_length=20)),
                ('followup_remarks', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'team2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_farmers', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team2_assignment', to='core.farmer')),
                ('team1_assignment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_followup', to='core.team1assignment')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
